name: sound_cat
channels:
  - conda-forge
  - defaults
dependencies:
  - aiofiles=22.1.0=pyhd8ed1ab_0
  - aiosqlite=0.18.0=pyhd8ed1ab_0
  - anyio=3.6.2=pyhd8ed1ab_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310h8e9501a_3
  - asttokens=2.2.1=pyhd8ed1ab_0
  - attrs=22.2.0=pyh71513ae_0
  - babel=2.12.1=pyhd8ed1ab_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.12.0=pyha770c72_0
  - blas=1.0=openblas
  - bleach=6.0.0=pyhd8ed1ab_0
  - bottleneck=1.3.5=py310h96f19d2_0
  - brotli=1.0.9=h1a28f6b_7
  - brotli-bin=1.0.9=h1a28f6b_7
  - brotlipy=0.7.0=py310h8e9501a_1005
  - bzip2=1.0.8=h620ffc9_4
  - ca-certificates=2023.01.10=hca03da5_0
  - certifi=2022.12.7=py310hca03da5_0
  - cffi=1.15.1=py310h2399d43_3
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - comm=0.1.3=pyhd8ed1ab_0
  - contourpy=1.0.5=py310h525c30c_0
  - cryptography=39.0.2=py310hfc83b78_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.6.6=py310h0f1eb42_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - flit-core=3.8.0=pyhd8ed1ab_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h1192e45_0
  - giflib=5.2.1=h80987f9_3
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.1.0=pyha770c72_0
  - importlib_metadata=6.1.0=hd8ed1ab_0
  - importlib_resources=5.12.0=pyhd8ed1ab_0
  - ipykernel=6.22.0=pyh736e0ef_0
  - ipython=8.11.0=pyhd1c38e8_0
  - ipython_genutils=0.2.0=py_1
  - jinja2=3.1.2=pyhd8ed1ab_1
  - jpeg=9e=h80987f9_1
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=4.17.3=pyhd8ed1ab_0
  - jupyter_client=8.1.0=pyhd8ed1ab_0
  - jupyter_core=5.3.0=py310hbe9552e_0
  - jupyter_events=0.6.3=pyhd8ed1ab_0
  - jupyter_server=2.5.0=pyhd8ed1ab_0
  - jupyter_server_fileid=0.8.0=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyter_server_ydoc=0.6.1=pyhd8ed1ab_0
  - jupyter_ydoc=0.2.3=pyhd8ed1ab_0
  - jupyterlab=3.6.1=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.21.0=pyhd8ed1ab_0
  - kiwisolver=1.4.4=py310h313beb8_0
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libbrotlicommon=1.0.9=h1a28f6b_7
  - libbrotlidec=1.0.9=h1a28f6b_7
  - libbrotlienc=1.0.9=h1a28f6b_7
  - libcxx=15.0.7=h75e25f2_0
  - libdeflate=1.17=h80987f9_0
  - libffi=3.4.2=hca03da5_6
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.40.0=h76d750c_0
  - libtiff=4.5.0=h313beb8_2
  - libwebp=1.2.4=ha3663a8_1
  - libwebp-base=1.2.4=h80987f9_1
  - libzlib=1.2.13=h03a7124_4
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_0
  - markupsafe=2.1.2=py310h8e9501a_0
  - matplotlib=3.7.1=py310hca03da5_1
  - matplotlib-base=3.7.1=py310h46d7db6_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mistune=2.0.5=pyhd8ed1ab_0
  - munkres=1.1.4=py_0
  - nbclassic=0.5.3=pyhb4ecaf3_3
  - nbclient=0.7.2=pyhd8ed1ab_0
  - nbconvert=7.2.9=pyhd8ed1ab_0
  - nbconvert-core=7.2.9=pyhd8ed1ab_0
  - nbconvert-pandoc=7.2.9=pyhd8ed1ab_0
  - nbformat=5.8.0=pyhd8ed1ab_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - notebook=6.5.3=pyha770c72_0
  - notebook-shim=0.2.2=pyhd8ed1ab_0
  - numexpr=2.8.4=py310hecc3335_0
  - numpy=1.23.5=py310hb93e574_0
  - numpy-base=1.23.5=py310haf87e8b_0
  - openssl=3.1.0=h03a7124_0
  - packaging=23.0=pyhd8ed1ab_0
  - pandas=1.5.3=py310h46d7db6_0
  - pandoc=2.19.2=hce30654_2
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py310h313beb8_0
  - pip=23.0.1=py310hca03da5_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
  - platformdirs=3.1.1=pyhd8ed1ab_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - prometheus_client=0.16.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - psutil=5.9.4=py310h8e9501a_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.14.0=pyhd8ed1ab_0
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=py310hca03da5_0
  - pyrsistent=0.19.3=py310h8e9501a_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.9=h3ba56d0_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-fastjsonschema=2.16.3=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python_abi=3.10=3_cp310
  - pytz=2022.7.1=pyhd8ed1ab_0
  - pyyaml=6.0=py310h8e9501a_5
  - pyzmq=25.0.2=py310hc407298_0
  - readline=8.2=h1a28f6b_0
  - requests=2.28.2=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - scipy=1.10.0=py310h20cbe94_1
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=65.6.3=py310hca03da5_0
  - six=1.16.0=pyh6c4a22f_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
  - sqlite=3.41.1=h80987f9_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - terminado=0.17.1=pyhd1c38e8_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.12=hb8d0fd4_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.2=py310h8e9501a_1
  - tqdm=4.65.0=py310h33ce5c2_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - tzdata=2022g=h04d1e81_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webencodings=0.5.1=py_1
  - websocket-client=1.5.1=pyhd8ed1ab_0
  - wheel=0.38.4=py310hca03da5_0
  - xz=5.2.10=h80987f9_1
  - y-py=0.5.9=py310h1dc5ec9_0
  - yaml=0.2.5=h3422bc3_2
  - ypy-websocket=0.8.2=pyhd8ed1ab_0
  - zeromq=4.3.4=hbdafb3b_1
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.2.13=h03a7124_4
  - zstd=1.5.2=h8574219_0
  - pip:
    - jedi==0.17.2
    - jupyterlab-tabnine==0.0.24
    - parso==0.7.1
    - pluggy==1.0.0
    - python-jsonrpc-server==0.4.0
    - python-language-server==0.36.2
    - seaborn==0.12.2
    - ujson==5.7.0
prefix: /Users/quentin/anaconda3/envs/sound_cat
